package statemove

import (
	"fmt"
	"strings"
)

const (
	shimBanner = "# Generated by `tfstackplan state move` — do not edit by hand."
	keyPrefix  = "# tfstackplan:key="
	opPrefix   = "# tfstackplan:op="
)

// Op is one operation in a shim file. Kind is "moved" (From→To, same state),
// "import" (To + ID, adopt into this state), or "removed" (From, drop from this
// state without destroying). Addresses/ids never contain a tab, so the header
// encodes ops tab-separated.
type Op struct {
	Kind string
	From string
	To   string
	ID   string
}

// RenderShim renders a PR-keyed shim: a machine-readable header (banner, key, one
// tab-separated op line each) followed by the native Terraform blocks. The header
// is the source of truth for list/maintenance.
func RenderShim(key string, ops []Op) string {
	var b strings.Builder
	b.WriteString(shimBanner + "\n")
	b.WriteString(keyPrefix + key + "\n")
	for _, o := range ops {
		fmt.Fprintf(&b, "%s%s\t%s\t%s\t%s\n", opPrefix, o.Kind, o.From, o.To, o.ID)
	}
	for _, o := range ops {
		switch o.Kind {
		case "moved":
			fmt.Fprintf(&b, "\nmoved {\n  from = %s\n  to   = %s\n}\n", o.From, o.To)
		case "import":
			fmt.Fprintf(&b, "\nimport {\n  to = %s\n  id = %q\n}\n", o.To, o.ID)
		case "removed":
			fmt.Fprintf(&b, "\nremoved {\n  from = %s\n  lifecycle {\n    destroy = false\n  }\n}\n", o.From)
		}
	}
	return b.String()
}

// ParseShim reads a shim's header back into key + ops. Errors if not a tfstackplan shim.
func ParseShim(content string) (key string, ops []Op, err error) {
	lines := strings.Split(content, "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != shimBanner {
		return "", nil, fmt.Errorf("not a tfstackplan state-move shim")
	}
	for _, ln := range lines {
		switch {
		case strings.HasPrefix(ln, keyPrefix):
			key = strings.TrimSpace(strings.TrimPrefix(ln, keyPrefix))
		case strings.HasPrefix(ln, opPrefix):
			f := strings.SplitN(strings.TrimPrefix(ln, opPrefix), "\t", 4)
			if len(f) != 4 {
				return "", nil, fmt.Errorf("malformed op line: %q", ln)
			}
			ops = append(ops, Op{Kind: f[0], From: f[1], To: f[2], ID: f[3]})
		}
	}
	if key == "" {
		return "", nil, fmt.Errorf("shim missing key header")
	}
	return key, ops, nil
}

// MergeOps appends add to existing, de-duplicating whole ops, preserving order.
func MergeOps(existing, add []Op) []Op {
	seen := map[Op]bool{}
	out := make([]Op, 0, len(existing)+len(add))
	for _, o := range append(append([]Op{}, existing...), add...) {
		if seen[o] {
			continue
		}
		seen[o] = true
		out = append(out, o)
	}
	return out
}
