package statemove

import (
	"fmt"
	"strings"
)

const (
	shimBanner = "# Generated by `tfstackplan state move` — do not edit by hand."
	keyPrefix  = "# tfstackplan:key="
	movePrefix = "# tfstackplan:move="
	moveArrow  = "=>" // address separator; Terraform addresses never contain "=>"
)

// RenderShim produces the .tf content for a PR-keyed set of same-stack moves: a
// machine-readable header (banner + key + one move line per pair) followed by the
// native `moved {}` blocks Terraform applies. The header is the source of truth
// for `list`/maintenance; the blocks are the functional output.
func RenderShim(key string, moves []Move) string {
	var b strings.Builder
	b.WriteString(shimBanner + "\n")
	b.WriteString(keyPrefix + key + "\n")
	for _, m := range moves {
		fmt.Fprintf(&b, "%s%s%s%s\n", movePrefix, m.From, moveArrow, m.To)
	}
	for _, m := range moves {
		fmt.Fprintf(&b, "\nmoved {\n  from = %s\n  to   = %s\n}\n", m.From, m.To)
	}
	return b.String()
}

// ParseShim reads a shim's header back into its key + moves. Errors if the
// content is not a tfstackplan shim (no banner/key).
func ParseShim(content string) (key string, moves []Move, err error) {
	lines := strings.Split(content, "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != shimBanner {
		return "", nil, fmt.Errorf("not a tfstackplan state-move shim")
	}
	for _, ln := range lines {
		switch {
		case strings.HasPrefix(ln, keyPrefix):
			key = strings.TrimSpace(strings.TrimPrefix(ln, keyPrefix))
		case strings.HasPrefix(ln, movePrefix):
			spec := strings.TrimPrefix(ln, movePrefix)
			from, to, ok := strings.Cut(spec, moveArrow)
			if !ok {
				return "", nil, fmt.Errorf("malformed move line: %q", ln)
			}
			moves = append(moves, Move{From: from, To: to})
		}
	}
	if key == "" {
		return "", nil, fmt.Errorf("shim missing key header")
	}
	return key, moves, nil
}

// MergeMoves appends new moves to existing, de-duplicating by (From,To),
// preserving order (existing first). Used to maintain a PR's shim across calls.
func MergeMoves(existing, add []Move) []Move {
	seen := map[Move]bool{}
	out := make([]Move, 0, len(existing)+len(add))
	for _, m := range append(append([]Move{}, existing...), add...) {
		if seen[m] {
			continue
		}
		seen[m] = true
		out = append(out, m)
	}
	return out
}
