package statemove

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hashicorp/hcl/v2/gohcl"
	"github.com/hashicorp/hcl/v2/hclparse"
)

const (
	xmovePrefix = "_tfsp_xmove."
	xmoveSuffix = ".hcl"
	xmoveBanner = "# Generated by `tfstackplan state move --via mv` — do not edit by hand. Executed by `tfstackplan state apply`."
)

// xmoveKeyFromFile extracts the key from an xmove manifest filename, or "" if the
// name isn't one of ours.
func xmoveKeyFromFile(name string) string {
	if strings.HasPrefix(name, xmovePrefix) && strings.HasSuffix(name, xmoveSuffix) {
		return name[len(xmovePrefix) : len(name)-len(xmoveSuffix)]
	}
	return ""
}

// XMove is a cross-state move manifest, colocated in the DESTINATION stack: pull
// the Pairs' source addresses out of SourceStack's state and into this stack's.
type XMove struct {
	SourceStack string
	Pairs       []Move
}

// XMoveFileName is the manifest filename for a key.
func XMoveFileName(key string) string { return xmovePrefix + key + xmoveSuffix }

// RenderXMove renders the HCL manifest (key in a header comment + an xmove block).
func RenderXMove(key string, xm XMove) string {
	var b strings.Builder
	b.WriteString(xmoveBanner + "\n")
	b.WriteString("# tfstackplan:key=" + key + "\n\n")
	b.WriteString("xmove {\n")
	fmt.Fprintf(&b, "  source_stack = %q\n", xm.SourceStack)
	b.WriteString("  moves = {\n")
	for _, m := range xm.Pairs {
		fmt.Fprintf(&b, "    %q = %q\n", m.From, m.To)
	}
	b.WriteString("  }\n}\n")
	return b.String()
}

type xmoveFile struct {
	XMove *struct {
		SourceStack string            `hcl:"source_stack"`
		Moves       map[string]string `hcl:"moves"`
	} `hcl:"xmove,block"`
}

// ParseXMove parses the manifest content into its key + XMove.
func ParseXMove(content string) (key string, xm XMove, err error) {
	for _, ln := range strings.Split(content, "\n") {
		if strings.HasPrefix(ln, "# tfstackplan:key=") {
			key = strings.TrimSpace(strings.TrimPrefix(ln, "# tfstackplan:key="))
		}
	}
	if key == "" {
		return "", XMove{}, fmt.Errorf("xmove manifest missing key header")
	}
	p := hclparse.NewParser()
	f, diags := p.ParseHCL([]byte(content), "xmove.hcl")
	if diags.HasErrors() {
		return "", XMove{}, fmt.Errorf("parse xmove: %s", diags.Error())
	}
	var decoded xmoveFile
	if diags := gohcl.DecodeBody(f.Body, nil, &decoded); diags.HasErrors() {
		return "", XMove{}, fmt.Errorf("decode xmove: %s", diags.Error())
	}
	if decoded.XMove == nil {
		return "", XMove{}, fmt.Errorf("xmove manifest has no xmove block")
	}
	xm.SourceStack = decoded.XMove.SourceStack
	froms := make([]string, 0, len(decoded.XMove.Moves))
	for k := range decoded.XMove.Moves {
		froms = append(froms, k)
	}
	sort.Strings(froms)
	for _, fr := range froms {
		xm.Pairs = append(xm.Pairs, Move{From: fr, To: decoded.XMove.Moves[fr]})
	}
	return key, xm, nil
}

// FoundXMove is a discovered manifest with its location.
type FoundXMove struct {
	Path      string
	DestStack string // dir relative to root (slash form)
	Key       string
	XMove     XMove
}

// DiscoverXMoves walks root for `_tfsp_xmove.*.hcl` manifests. It is fail-closed:
// a file in our reserved namespace that won't parse, or whose header key
// disagrees with its filename, returns an error (the filename is authoritative).
// Use CleanupXMoves to remove such a file.
func DiscoverXMoves(root string) ([]FoundXMove, error) {
	var out []FoundXMove
	err := walkManifestFiles(root, xmoveKeyFromFile, func(path, fileKey string) error {
		data, rerr := os.ReadFile(path)
		if rerr != nil {
			return rerr
		}
		key, xm, perr := ParseXMove(string(data))
		if perr != nil {
			return fmt.Errorf("xmove manifest %s: %w", path, perr)
		}
		if key != fileKey {
			return fmt.Errorf("xmove manifest %s: key mismatch (filename %q != header %q)", path, fileKey, key)
		}
		rel, _ := filepath.Rel(root, filepath.Dir(path))
		out = append(out, FoundXMove{Path: path, DestStack: filepath.ToSlash(rel), Key: fileKey, XMove: xm})
		return nil
	})
	return out, err
}
