//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/Fluent-Health/terraform-stack-plan/internal/events"
	"github.com/oapi-codegen/runtime"
)

const (
	OidcScopes oidcContextKey = "oidc.Scopes"
)

// Category A classification label matched by a stack.
type Category = events.Category

// Claim One apply-lock claim row.
type Claim = events.Claim

// ClaimsListRequest defines model for ClaimsListRequest.
type ClaimsListRequest struct {
	Environment string `json:"environment"`
}

// ClaimsReleaseRequest defines model for ClaimsReleaseRequest.
type ClaimsReleaseRequest struct {
	Environment string `json:"environment"`
	Pr          int    `json:"pr"`

	// Stack Empty releases all of the PR's claims in the environment.
	Stack string `json:"stack"`
}

// CodedError Machine-readable error: HTTP status carries the coarse class, code the precise condition callers switch on.
type CodedError struct {
	// Code e.g. GATE-001, GATE-002, GATE-003, SRV-001
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Counts A stack's per-kind operation tally (zero counts omitted).
type Counts = events.Counts

// Edge A dependency: from must run before to.
type Edge = events.Edge

// ExecutionDetail The full execution read. Top-level and gate keys are PascalCase with a raw NullInt64 (see getExecution).
type ExecutionDetail struct {
	// CheckRunID A database nullable int64, serialized raw (historical accident, preserved for wire compatibility).
	CheckRunID     NullInt64 `json:"CheckRunID"`
	CreatedAt      time.Time `json:"CreatedAt"`
	Environment    string    `json:"Environment"`
	ID             string    `json:"ID"`
	LogURL         string    `json:"LogURL"`
	PR             int       `json:"PR"`
	Phase          string    `json:"Phase"`
	Repo           string    `json:"Repo"`
	ReportMarkdown string    `json:"ReportMarkdown"`
	Rev            int       `json:"Rev"`
	SHA            string    `json:"SHA"`

	// Status Execution-level status (in_progress/success/failure).
	Status        string             `json:"Status"`
	StatusContext string             `json:"StatusContext"`
	SupersededBy  string             `json:"SupersededBy"`
	Gates         []StoredGateTarget `json:"gates"`

	// Graph The changed subgraph for one execution.
	Graph Graph `json:"graph"`

	// VerifyExecutionId Latest verify execution for the same (pr, environment), "" when none. Additive (2026-07) — snake_case unlike its legacy siblings.
	VerifyExecutionId string `json:"verify_execution_id"`
}

// ExecutionSummary One execution in a list view — everything but the graph and the rendered report.
type ExecutionSummary struct {
	// Context The commit-status context the run drives (e.g. plan/<env>, apply/<env>, verify/<env>).
	Context     string    `json:"context"`
	CreatedAt   time.Time `json:"created_at"`
	Environment string    `json:"environment"`
	Id          string    `json:"id"`
	LogUrl      string    `json:"log_url"`

	// Phase Current lifecycle phase ("" before the first phase event).
	Phase string `json:"phase"`
	Pr    int    `json:"pr"`
	Repo  string `json:"repo"`
	Sha   string `json:"sha"`

	// Status Execution-level status (in_progress/success/failure).
	Status string `json:"status"`

	// SupersededBy Id of the execution that superseded this one ("" when live).
	SupersededBy string `json:"superseded_by"`
}

// Finalize Records the terminal plan state.
type Finalize = events.Finalize

// GateCheck defines model for GateCheck.
type GateCheck = events.GateCheck

// GateCheckOK A passing gate check.
type GateCheckOK struct {
	// Requester Leased requester SA the apply impersonates; empty for a clean/no-gate pass.
	Requester string `json:"requester"`
}

// GateRevoke defines model for GateRevoke.
type GateRevoke = events.GateRevoke

// GateTarget One thing that must be approved: a classification class against a target (e.g. a cloud project).
type GateTarget = events.GateTarget

// Graph The changed subgraph for one execution.
type Graph = events.Graph

// Init Registers an execution and its changed subgraph.
type Init = events.Init

// LogChunk A slice of one stack's combined output.
type LogChunk = events.LogChunk

// NullInt64 A database nullable int64, serialized raw (historical accident, preserved for wire compatibility).
type NullInt64 struct {
	Int64 int64 `json:"Int64"`
	Valid bool  `json:"Valid"`
}

// PendingApproval One gate target awaiting human action, with its PR context.
type PendingApproval struct {
	Class       string `json:"class"`
	Environment string `json:"environment"`

	// GrantName The approval-backend grant resource name ("" until a grant exists).
	GrantName string `json:"grant_name"`
	Pr        int    `json:"pr"`

	// Repo Repo of the PR's latest execution in this environment ("" when none).
	Repo string `json:"repo"`

	// Requester Leased requester SA for this grant.
	Requester string `json:"requester"`

	// State Backend grant state (e.g. AWAITING, ACTIVATING, DENIED, REVOKED).
	State  string `json:"state"`
	Target string `json:"target"`
}

// Phase Execution-wide lifecycle phase.
type Phase = events.Phase

// PhaseEvent Narrates a lifecycle phase transition (may arrive before Init).
type PhaseEvent = events.PhaseEvent

// StackState One node in the execution graph.
type StackState = events.StackState

// Status Per-stack lifecycle status. Decoding rejects unknown non-empty values (WIRE-001); an omitted/empty status is tolerated.
type Status = events.Status

// StoredGateTarget A recorded gate target with its grant state (PascalCase keys).
type StoredGateTarget struct {
	Class string `json:"Class"`

	// GrantName The approval-backend grant resource name (may be empty).
	GrantName string `json:"GrantName"`

	// Requester Leased requester SA for this grant.
	Requester string `json:"Requester"`

	// State Backend grant state (e.g. REQUESTED, ACTIVE, DENIED, REVOKED).
	State  string `json:"State"`
	Target string `json:"Target"`
}

// Update Ticks a single stack's status.
type Update = events.Update

// oidcContextKey is the context key for oidc security scheme
type oidcContextKey string

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	// Pr Only executions for this pull request.
	Pr    *int `form:"pr,omitempty" json:"pr,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListClaimsJSONRequestBody defines body for ListClaims for application/json ContentType.
type ListClaimsJSONRequestBody = ClaimsListRequest

// ReleaseClaimsJSONRequestBody defines body for ReleaseClaims for application/json ContentType.
type ReleaseClaimsJSONRequestBody = ClaimsReleaseRequest

// FinalizeExecutionJSONRequestBody defines body for FinalizeExecution for application/json ContentType.
type FinalizeExecutionJSONRequestBody = Finalize

// CheckGateJSONRequestBody defines body for CheckGate for application/json ContentType.
type CheckGateJSONRequestBody = GateCheck

// RevokeGateJSONRequestBody defines body for RevokeGate for application/json ContentType.
type RevokeGateJSONRequestBody = GateRevoke

// InitExecutionJSONRequestBody defines body for InitExecution for application/json ContentType.
type InitExecutionJSONRequestBody = Init

// AppendLogsJSONRequestBody defines body for AppendLogs for application/json ContentType.
type AppendLogsJSONRequestBody = LogChunk

// ReportPhaseJSONRequestBody defines body for ReportPhase for application/json ContentType.
type ReportPhaseJSONRequestBody = PhaseEvent

// UpdateStackJSONRequestBody defines body for UpdateStack for application/json ContentType.
type UpdateStackJSONRequestBody = Update

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListApprovals request
	ListApprovals(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListClaimsWithBody request with any body
	ListClaimsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ListClaims(ctx context.Context, body ListClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReleaseClaimsWithBody request with any body
	ReleaseClaimsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReleaseClaims(ctx context.Context, body ReleaseClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetExecution request
	GetExecution(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListExecutions request
	ListExecutions(ctx context.Context, params *ListExecutionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FinalizeExecutionWithBody request with any body
	FinalizeExecutionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	FinalizeExecution(ctx context.Context, body FinalizeExecutionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckGateWithBody request with any body
	CheckGateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CheckGate(ctx context.Context, body CheckGateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeGateWithBody request with any body
	RevokeGateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RevokeGate(ctx context.Context, body RevokeGateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InitExecutionWithBody request with any body
	InitExecutionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InitExecution(ctx context.Context, body InitExecutionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AppendLogsWithBody request with any body
	AppendLogsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AppendLogs(ctx context.Context, body AppendLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReportPhaseWithBody request with any body
	ReportPhaseWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReportPhase(ctx context.Context, body ReportPhaseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateStackWithBody request with any body
	UpdateStackWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateStack(ctx context.Context, body UpdateStackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListApprovals(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListApprovalsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListClaimsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListClaimsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListClaims(ctx context.Context, body ListClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListClaimsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReleaseClaimsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReleaseClaimsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReleaseClaims(ctx context.Context, body ReleaseClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReleaseClaimsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetExecution(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetExecutionRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListExecutions(ctx context.Context, params *ListExecutionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListExecutionsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinalizeExecutionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinalizeExecutionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinalizeExecution(ctx context.Context, body FinalizeExecutionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinalizeExecutionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CheckGateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckGateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CheckGate(ctx context.Context, body CheckGateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckGateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeGateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeGateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeGate(ctx context.Context, body RevokeGateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeGateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitExecutionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitExecutionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitExecution(ctx context.Context, body InitExecutionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitExecutionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AppendLogsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppendLogsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AppendLogs(ctx context.Context, body AppendLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppendLogsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReportPhaseWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReportPhaseRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReportPhase(ctx context.Context, body ReportPhaseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReportPhaseRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateStackWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateStackRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateStack(ctx context.Context, body UpdateStackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateStackRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListApprovalsRequest generates requests for ListApprovals
func NewListApprovalsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/approvals")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListClaimsRequest calls the generic ListClaims builder with application/json body
func NewListClaimsRequest(server string, body ListClaimsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewListClaimsRequestWithBody(server, "application/json", bodyReader)
}

// NewListClaimsRequestWithBody generates requests for ListClaims with any type of body
func NewListClaimsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/claims/list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReleaseClaimsRequest calls the generic ReleaseClaims builder with application/json body
func NewReleaseClaimsRequest(server string, body ReleaseClaimsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReleaseClaimsRequestWithBody(server, "application/json", bodyReader)
}

// NewReleaseClaimsRequestWithBody generates requests for ReleaseClaims with any type of body
func NewReleaseClaimsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/claims/release")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetExecutionRequest generates requests for GetExecution
func NewGetExecutionRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/execution/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListExecutionsRequest generates requests for ListExecutions
func NewListExecutionsRequest(server string, params *ListExecutionsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/executions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Pr != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pr", *params.Pr, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinalizeExecutionRequest calls the generic FinalizeExecution builder with application/json body
func NewFinalizeExecutionRequest(server string, body FinalizeExecutionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFinalizeExecutionRequestWithBody(server, "application/json", bodyReader)
}

// NewFinalizeExecutionRequestWithBody generates requests for FinalizeExecution with any type of body
func NewFinalizeExecutionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/finalize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCheckGateRequest calls the generic CheckGate builder with application/json body
func NewCheckGateRequest(server string, body CheckGateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCheckGateRequestWithBody(server, "application/json", bodyReader)
}

// NewCheckGateRequestWithBody generates requests for CheckGate with any type of body
func NewCheckGateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/gate/check")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRevokeGateRequest calls the generic RevokeGate builder with application/json body
func NewRevokeGateRequest(server string, body RevokeGateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRevokeGateRequestWithBody(server, "application/json", bodyReader)
}

// NewRevokeGateRequestWithBody generates requests for RevokeGate with any type of body
func NewRevokeGateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/gate/revoke")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInitExecutionRequest calls the generic InitExecution builder with application/json body
func NewInitExecutionRequest(server string, body InitExecutionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInitExecutionRequestWithBody(server, "application/json", bodyReader)
}

// NewInitExecutionRequestWithBody generates requests for InitExecution with any type of body
func NewInitExecutionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/init")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAppendLogsRequest calls the generic AppendLogs builder with application/json body
func NewAppendLogsRequest(server string, body AppendLogsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAppendLogsRequestWithBody(server, "application/json", bodyReader)
}

// NewAppendLogsRequestWithBody generates requests for AppendLogs with any type of body
func NewAppendLogsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReportPhaseRequest calls the generic ReportPhase builder with application/json body
func NewReportPhaseRequest(server string, body ReportPhaseJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReportPhaseRequestWithBody(server, "application/json", bodyReader)
}

// NewReportPhaseRequestWithBody generates requests for ReportPhase with any type of body
func NewReportPhaseRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/phase")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateStackRequest calls the generic UpdateStack builder with application/json body
func NewUpdateStackRequest(server string, body UpdateStackJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateStackRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateStackRequestWithBody generates requests for UpdateStack with any type of body
func NewUpdateStackRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/update")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListApprovalsWithResponse request
	ListApprovalsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListApprovalsResponse, error)

	// ListClaimsWithBodyWithResponse request with any body
	ListClaimsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListClaimsResponse, error)

	ListClaimsWithResponse(ctx context.Context, body ListClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListClaimsResponse, error)

	// ReleaseClaimsWithBodyWithResponse request with any body
	ReleaseClaimsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReleaseClaimsResponse, error)

	ReleaseClaimsWithResponse(ctx context.Context, body ReleaseClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*ReleaseClaimsResponse, error)

	// GetExecutionWithResponse request
	GetExecutionWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetExecutionResponse, error)

	// ListExecutionsWithResponse request
	ListExecutionsWithResponse(ctx context.Context, params *ListExecutionsParams, reqEditors ...RequestEditorFn) (*ListExecutionsResponse, error)

	// FinalizeExecutionWithBodyWithResponse request with any body
	FinalizeExecutionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinalizeExecutionResponse, error)

	FinalizeExecutionWithResponse(ctx context.Context, body FinalizeExecutionJSONRequestBody, reqEditors ...RequestEditorFn) (*FinalizeExecutionResponse, error)

	// CheckGateWithBodyWithResponse request with any body
	CheckGateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckGateResponse, error)

	CheckGateWithResponse(ctx context.Context, body CheckGateJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckGateResponse, error)

	// RevokeGateWithBodyWithResponse request with any body
	RevokeGateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RevokeGateResponse, error)

	RevokeGateWithResponse(ctx context.Context, body RevokeGateJSONRequestBody, reqEditors ...RequestEditorFn) (*RevokeGateResponse, error)

	// InitExecutionWithBodyWithResponse request with any body
	InitExecutionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitExecutionResponse, error)

	InitExecutionWithResponse(ctx context.Context, body InitExecutionJSONRequestBody, reqEditors ...RequestEditorFn) (*InitExecutionResponse, error)

	// AppendLogsWithBodyWithResponse request with any body
	AppendLogsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppendLogsResponse, error)

	AppendLogsWithResponse(ctx context.Context, body AppendLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*AppendLogsResponse, error)

	// ReportPhaseWithBodyWithResponse request with any body
	ReportPhaseWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReportPhaseResponse, error)

	ReportPhaseWithResponse(ctx context.Context, body ReportPhaseJSONRequestBody, reqEditors ...RequestEditorFn) (*ReportPhaseResponse, error)

	// UpdateStackWithBodyWithResponse request with any body
	UpdateStackWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateStackResponse, error)

	UpdateStackWithResponse(ctx context.Context, body UpdateStackJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateStackResponse, error)
}

type ListApprovalsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]PendingApproval
}

// Status returns HTTPResponse.Status
func (r ListApprovalsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListApprovalsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListApprovalsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListClaimsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Claim
}

// Status returns HTTPResponse.Status
func (r ListClaimsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListClaimsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListClaimsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReleaseClaimsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ReleaseClaimsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReleaseClaimsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReleaseClaimsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetExecutionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ExecutionDetail
}

// Status returns HTTPResponse.Status
func (r GetExecutionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetExecutionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetExecutionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListExecutionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ExecutionSummary
}

// Status returns HTTPResponse.Status
func (r ListExecutionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListExecutionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListExecutionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FinalizeExecutionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinalizeExecutionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinalizeExecutionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FinalizeExecutionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CheckGateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GateCheckOK
	JSON409      *CodedError
	JSON500      *CodedError
	JSON503      *CodedError
}

// Status returns HTTPResponse.Status
func (r CheckGateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CheckGateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CheckGateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RevokeGateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r RevokeGateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeGateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RevokeGateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type InitExecutionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r InitExecutionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InitExecutionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r InitExecutionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AppendLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r AppendLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AppendLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AppendLogsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReportPhaseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ReportPhaseResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReportPhaseResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReportPhaseResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateStackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UpdateStackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateStackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateStackResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListApprovalsWithResponse request returning *ListApprovalsResponse
func (c *ClientWithResponses) ListApprovalsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListApprovalsResponse, error) {
	rsp, err := c.ListApprovals(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListApprovalsResponse(rsp)
}

// ListClaimsWithBodyWithResponse request with arbitrary body returning *ListClaimsResponse
func (c *ClientWithResponses) ListClaimsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListClaimsResponse, error) {
	rsp, err := c.ListClaimsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListClaimsResponse(rsp)
}

func (c *ClientWithResponses) ListClaimsWithResponse(ctx context.Context, body ListClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListClaimsResponse, error) {
	rsp, err := c.ListClaims(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListClaimsResponse(rsp)
}

// ReleaseClaimsWithBodyWithResponse request with arbitrary body returning *ReleaseClaimsResponse
func (c *ClientWithResponses) ReleaseClaimsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReleaseClaimsResponse, error) {
	rsp, err := c.ReleaseClaimsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReleaseClaimsResponse(rsp)
}

func (c *ClientWithResponses) ReleaseClaimsWithResponse(ctx context.Context, body ReleaseClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*ReleaseClaimsResponse, error) {
	rsp, err := c.ReleaseClaims(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReleaseClaimsResponse(rsp)
}

// GetExecutionWithResponse request returning *GetExecutionResponse
func (c *ClientWithResponses) GetExecutionWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetExecutionResponse, error) {
	rsp, err := c.GetExecution(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetExecutionResponse(rsp)
}

// ListExecutionsWithResponse request returning *ListExecutionsResponse
func (c *ClientWithResponses) ListExecutionsWithResponse(ctx context.Context, params *ListExecutionsParams, reqEditors ...RequestEditorFn) (*ListExecutionsResponse, error) {
	rsp, err := c.ListExecutions(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListExecutionsResponse(rsp)
}

// FinalizeExecutionWithBodyWithResponse request with arbitrary body returning *FinalizeExecutionResponse
func (c *ClientWithResponses) FinalizeExecutionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FinalizeExecutionResponse, error) {
	rsp, err := c.FinalizeExecutionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinalizeExecutionResponse(rsp)
}

func (c *ClientWithResponses) FinalizeExecutionWithResponse(ctx context.Context, body FinalizeExecutionJSONRequestBody, reqEditors ...RequestEditorFn) (*FinalizeExecutionResponse, error) {
	rsp, err := c.FinalizeExecution(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinalizeExecutionResponse(rsp)
}

// CheckGateWithBodyWithResponse request with arbitrary body returning *CheckGateResponse
func (c *ClientWithResponses) CheckGateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckGateResponse, error) {
	rsp, err := c.CheckGateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckGateResponse(rsp)
}

func (c *ClientWithResponses) CheckGateWithResponse(ctx context.Context, body CheckGateJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckGateResponse, error) {
	rsp, err := c.CheckGate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckGateResponse(rsp)
}

// RevokeGateWithBodyWithResponse request with arbitrary body returning *RevokeGateResponse
func (c *ClientWithResponses) RevokeGateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RevokeGateResponse, error) {
	rsp, err := c.RevokeGateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeGateResponse(rsp)
}

func (c *ClientWithResponses) RevokeGateWithResponse(ctx context.Context, body RevokeGateJSONRequestBody, reqEditors ...RequestEditorFn) (*RevokeGateResponse, error) {
	rsp, err := c.RevokeGate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeGateResponse(rsp)
}

// InitExecutionWithBodyWithResponse request with arbitrary body returning *InitExecutionResponse
func (c *ClientWithResponses) InitExecutionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitExecutionResponse, error) {
	rsp, err := c.InitExecutionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitExecutionResponse(rsp)
}

func (c *ClientWithResponses) InitExecutionWithResponse(ctx context.Context, body InitExecutionJSONRequestBody, reqEditors ...RequestEditorFn) (*InitExecutionResponse, error) {
	rsp, err := c.InitExecution(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitExecutionResponse(rsp)
}

// AppendLogsWithBodyWithResponse request with arbitrary body returning *AppendLogsResponse
func (c *ClientWithResponses) AppendLogsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppendLogsResponse, error) {
	rsp, err := c.AppendLogsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppendLogsResponse(rsp)
}

func (c *ClientWithResponses) AppendLogsWithResponse(ctx context.Context, body AppendLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*AppendLogsResponse, error) {
	rsp, err := c.AppendLogs(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppendLogsResponse(rsp)
}

// ReportPhaseWithBodyWithResponse request with arbitrary body returning *ReportPhaseResponse
func (c *ClientWithResponses) ReportPhaseWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReportPhaseResponse, error) {
	rsp, err := c.ReportPhaseWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReportPhaseResponse(rsp)
}

func (c *ClientWithResponses) ReportPhaseWithResponse(ctx context.Context, body ReportPhaseJSONRequestBody, reqEditors ...RequestEditorFn) (*ReportPhaseResponse, error) {
	rsp, err := c.ReportPhase(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReportPhaseResponse(rsp)
}

// UpdateStackWithBodyWithResponse request with arbitrary body returning *UpdateStackResponse
func (c *ClientWithResponses) UpdateStackWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateStackResponse, error) {
	rsp, err := c.UpdateStackWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateStackResponse(rsp)
}

func (c *ClientWithResponses) UpdateStackWithResponse(ctx context.Context, body UpdateStackJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateStackResponse, error) {
	rsp, err := c.UpdateStack(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateStackResponse(rsp)
}

// ParseListApprovalsResponse parses an HTTP response from a ListApprovalsWithResponse call
func ParseListApprovalsResponse(rsp *http.Response) (*ListApprovalsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListApprovalsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []PendingApproval
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListClaimsResponse parses an HTTP response from a ListClaimsWithResponse call
func ParseListClaimsResponse(rsp *http.Response) (*ListClaimsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListClaimsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Claim
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseReleaseClaimsResponse parses an HTTP response from a ReleaseClaimsWithResponse call
func ParseReleaseClaimsResponse(rsp *http.Response) (*ReleaseClaimsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReleaseClaimsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetExecutionResponse parses an HTTP response from a GetExecutionWithResponse call
func ParseGetExecutionResponse(rsp *http.Response) (*GetExecutionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetExecutionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ExecutionDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListExecutionsResponse parses an HTTP response from a ListExecutionsWithResponse call
func ParseListExecutionsResponse(rsp *http.Response) (*ListExecutionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListExecutionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ExecutionSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFinalizeExecutionResponse parses an HTTP response from a FinalizeExecutionWithResponse call
func ParseFinalizeExecutionResponse(rsp *http.Response) (*FinalizeExecutionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinalizeExecutionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCheckGateResponse parses an HTTP response from a CheckGateWithResponse call
func ParseCheckGateResponse(rsp *http.Response) (*CheckGateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CheckGateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GateCheckOK
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest CodedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest CodedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest CodedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseRevokeGateResponse parses an HTTP response from a RevokeGateWithResponse call
func ParseRevokeGateResponse(rsp *http.Response) (*RevokeGateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeGateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseInitExecutionResponse parses an HTTP response from a InitExecutionWithResponse call
func ParseInitExecutionResponse(rsp *http.Response) (*InitExecutionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InitExecutionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseAppendLogsResponse parses an HTTP response from a AppendLogsWithResponse call
func ParseAppendLogsResponse(rsp *http.Response) (*AppendLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AppendLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseReportPhaseResponse parses an HTTP response from a ReportPhaseWithResponse call
func ParseReportPhaseResponse(rsp *http.Response) (*ReportPhaseResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReportPhaseResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUpdateStackResponse parses an HTTP response from a UpdateStackWithResponse call
func ParseUpdateStackResponse(rsp *http.Response) (*UpdateStackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateStackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List gate targets awaiting human action, across all PRs
	// (GET /api/approvals)
	ListApprovals(w http.ResponseWriter, r *http.Request)
	// List the apply-lock claims for an environment
	// (POST /api/claims/list)
	ListClaims(w http.ResponseWriter, r *http.Request)
	// Admin-release one stack's claim or all of a PR's claims
	// (POST /api/claims/release)
	ReleaseClaims(w http.ResponseWriter, r *http.Request)
	// Read one execution's full state
	// (GET /api/execution/{id})
	GetExecution(w http.ResponseWriter, r *http.Request, id string)
	// List executions, newest first
	// (GET /api/executions)
	ListExecutions(w http.ResponseWriter, r *http.Request, params ListExecutionsParams)
	// Record the terminal plan state
	// (POST /api/finalize)
	FinalizeExecution(w http.ResponseWriter, r *http.Request)
	// Apply-time, fail-closed gate pre-check
	// (POST /api/gate/check)
	CheckGate(w http.ResponseWriter, r *http.Request)
	// Revoke the grants requested for (pr, environment)
	// (POST /api/gate/revoke)
	RevokeGate(w http.ResponseWriter, r *http.Request)
	// Register an execution and its changed subgraph
	// (POST /api/init)
	InitExecution(w http.ResponseWriter, r *http.Request)
	// Ingest a per-stack output chunk
	// (POST /api/logs)
	AppendLogs(w http.ResponseWriter, r *http.Request)
	// Narrate a lifecycle phase transition
	// (POST /api/phase)
	ReportPhase(w http.ResponseWriter, r *http.Request)
	// Tick a single stack's status
	// (POST /api/update)
	UpdateStack(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApprovals operation middleware
func (siw *ServerInterfaceWrapper) ListApprovals(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report", "read", "admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApprovals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClaims operation middleware
func (siw *ServerInterfaceWrapper) ListClaims(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report", "read", "admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClaims(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReleaseClaims operation middleware
func (siw *ServerInterfaceWrapper) ReleaseClaims(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report", "admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReleaseClaims(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecution operation middleware
func (siw *ServerInterfaceWrapper) GetExecution(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report", "read", "admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecution(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListExecutions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report", "read", "admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionsParams

	// ------------- Optional query parameter "pr" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pr", r.URL.Query(), &params.Pr, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pr"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pr", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FinalizeExecution operation middleware
func (siw *ServerInterfaceWrapper) FinalizeExecution(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FinalizeExecution(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckGate operation middleware
func (siw *ServerInterfaceWrapper) CheckGate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckGate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeGate operation middleware
func (siw *ServerInterfaceWrapper) RevokeGate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeGate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InitExecution operation middleware
func (siw *ServerInterfaceWrapper) InitExecution(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InitExecution(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AppendLogs operation middleware
func (siw *ServerInterfaceWrapper) AppendLogs(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppendLogs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportPhase operation middleware
func (siw *ServerInterfaceWrapper) ReportPhase(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportPhase(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateStack operation middleware
func (siw *ServerInterfaceWrapper) UpdateStack(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OidcScopes, []string{"report"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateStack(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/approvals", wrapper.ListApprovals)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/claims/list", wrapper.ListClaims)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/claims/release", wrapper.ReleaseClaims)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/execution/{id}", wrapper.GetExecution)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/executions", wrapper.ListExecutions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/finalize", wrapper.FinalizeExecution)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/gate/check", wrapper.CheckGate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/gate/revoke", wrapper.RevokeGate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/init", wrapper.InitExecution)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/logs", wrapper.AppendLogs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/phase", wrapper.ReportPhase)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/update", wrapper.UpdateStack)

	return m
}
