/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an execution and its changed subgraph
         * @description Idempotent per execution id — a repeat Init resets per-stack statuses
         *     to the payload values but never regresses an already-advanced stack.
         *     Creates/refreshes the GitHub check run and may supersede a live
         *     same-(pr, environment) execution for an older SHA.
         */
        post: operations["initExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Narrate a lifecycle phase transition
         * @description May arrive before Init; the execution row is upserted.
         */
        post: operations["reportPhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tick a single stack's status */
        post: operations["updateStack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record the terminal plan state
         * @description Persists the rendered report and per-stack backfills, records the gate
         *     targets through the reconcile core (requesting approval grants), and
         *     drives the terminal check-run conclusion.
         */
        post: operations["finalizeExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a per-stack output chunk */
        post: operations["appendLogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gate/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply-time, fail-closed gate pre-check
         * @description 200 only when the (pr, environment) was classified AND every recorded
         *     gate target's grant is ACTIVE (a classified plan with no gates passes,
         *     with an empty requester). Reconciles against the approval backend
         *     first; when current grant state cannot be confirmed the check fails
         *     closed with 503 `GATE-003` rather than trusting a stale cache.
         */
        post: operations["checkGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gate/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the grants requested for (pr, environment)
         * @description Best-effort post-apply cleanup; also releases the apply-lock claim. Always 200 — revoke failures are logged server-side, not surfaced.
         */
        post: operations["revokeGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claims/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List the apply-lock claims for an environment */
        post: operations["listClaims"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claims/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin-release one stack's claim or all of a PR's claims
         * @description stack != "" releases that stack's claim; stack == "" releases every claim the PR holds in the environment. Always 200 (best-effort).
         */
        post: operations["releaseClaims"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List executions, newest first
         * @description The recent-executions feed (default 100, cap 1000). `pr` filters to one
         *     pull request's full timeline across plan/apply/verify runs. Summaries
         *     deliberately exclude the rendered report — fetch one execution for
         *     that.
         */
        get: operations["listExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List gate targets awaiting human action, across all PRs
         * @description Every recorded gate target not yet ACTIVE, with the PR context an
         *     approvals surface needs (repo from the PR's latest execution in that
         *     environment) and the grant resource name an approval call targets.
         *     DENIED/REVOKED targets are included — they need attention even though
         *     the action is not "approve".
         */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pr/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a pull request's identity and per-tier merge state
         * @description PR identity (title/author/branch/automerge, as last reported by the
         *     GitHub webhook) plus this serve tier's merge-readiness verdict (the
         *     required check and apply-lock state for `a.cfg.Environment`). `meta`
         *     is omitted when no metadata row has been recorded for the PR. 404
         *     when the PR is entirely unknown to this tier (no metadata and no
         *     execution).
         */
        get: operations["getPR"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execution/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one execution's full state
         * @description The execution row, its stack/edge graph, and the gate targets for its
         *     (pr, environment). NOTE the response's top-level and `gates` keys are
         *     PascalCase and `CheckRunID` is a raw `{Int64, Valid}` pair — a
         *     historical accident preserved for wire compatibility.
         */
        get: operations["getExecution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspect/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all recorded grants */
        get: operations["inspectGrants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspect/gate/{pr}/{env}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get gate state explainer and reason trail */
        get: operations["inspectGate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspect/claims/{env}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get folded claim set for an environment */
        get: operations["inspectClaims"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspect/events/{stream}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ordered events for a stream */
        get: operations["inspectEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspect/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System-wide overview of all active PR states */
        get: operations["inspectOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspect/pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get applier-pool slot occupancy and waiting lists */
        get: operations["inspectPool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/grants/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin release a gate grant */
        post: operations["adminGrantsRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/executions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin cancel a running execution */
        post: operations["adminExecutionsCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/gates/satisfy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin satisfy a gate target manually */
        post: operations["adminGatesSatisfy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/checks/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin override a check conclusion */
        post: operations["adminChecksOverride"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminGrantsReleaseRequest: {
            pr: number;
            environment: string;
            class: string;
            target: string;
            reason: string;
        };
        AdminExecutionsCancelRequest: {
            id: string;
            reason: string;
        };
        AdminGatesSatisfyRequest: {
            pr: number;
            environment: string;
            class: string;
            target: string;
            reason: string;
        };
        AdminChecksOverrideRequest: {
            pr: number;
            environment: string;
            check: string;
            conclusion: string;
            reason: string;
        };
        /**
         * @description Per-stack lifecycle status. Decoding rejects unknown non-empty values (WIRE-001); an omitted/empty status is tolerated.
         * @enum {string}
         */
        Status: "pending" | "initializing" | "initialized" | "running" | "planned" | "gated" | "safe" | "nochange" | "moving" | "failed" | "aborted";
        /**
         * @description Execution-wide lifecycle phase.
         * @enum {string}
         */
        Phase: "warming" | "linting" | "initializing" | "planning" | "applying" | "testing" | "verifying";
        /** @description A classification label matched by a stack. */
        Category: {
            name: string;
            icon?: string;
            attributes?: {
                [key: string]: string[];
            };
        };
        /** @description A stack's per-kind operation tally (zero counts omitted). */
        Counts: {
            add?: number;
            change?: number;
            destroy?: number;
            replace?: number;
            move?: number;
            import?: number;
            forget?: number;
            sensitivity_only?: number;
        };
        /** @description One node in the execution graph. */
        StackState: {
            path: string;
            /** @description Grouping/target key (e.g. cloud project/account). */
            project?: string;
            status?: components["schemas"]["Status"];
            /** @description Optional failure detail (last error lines). */
            detail?: string;
            categories?: components["schemas"]["Category"][];
            counts?: components["schemas"]["Counts"];
        };
        /** @description A dependency: from must run before to. */
        Edge: {
            from: string;
            to: string;
        };
        /** @description The changed subgraph for one execution. */
        Graph: {
            /** @description Always an array — empty (never null) for a zero-stack execution. */
            stacks: components["schemas"]["StackState"][];
            /** @description Always an array, never null (serves < v0.25.2 emitted null). */
            edges: components["schemas"]["Edge"][];
        };
        /** @description One thing that must be approved: a classification class against a target (e.g. a cloud project). */
        GateTarget: {
            class: string;
            target: string;
        };
        /** @description Registers an execution and its changed subgraph. */
        Init: {
            id: string;
            repo: string;
            sha: string;
            pr: number;
            environment: string;
            /** @description CI log deep-link, shown on failures. */
            log_url: string;
            /** @description Commit-status context this run drives. */
            context?: string;
            stacks: components["schemas"]["StackState"][];
            edges: components["schemas"]["Edge"][] | null;
        };
        /** @description Narrates a lifecycle phase transition (may arrive before Init). */
        PhaseEvent: {
            id: string;
            repo?: string;
            sha?: string;
            pr?: number;
            environment?: string;
            log_url?: string;
            context?: string;
            phase: components["schemas"]["Phase"];
        };
        /** @description Ticks a single stack's status. */
        Update: {
            id: string;
            stack: string;
            status: components["schemas"]["Status"];
            detail?: string;
        };
        /** @description Records the terminal plan state. */
        Finalize: {
            id: string;
            report_markdown: string;
            /** @description Stack path → grouping/target key. */
            projects?: {
                [key: string]: string;
            };
            /** @description Stack path → rendered plan section (markdown). */
            stack_reports?: {
                [key: string]: string;
            };
            /** @description (class, target) pairs needing approval. */
            gates?: components["schemas"]["GateTarget"][];
            /** @description Stack paths adopting resources via a cross-state move. */
            moving?: string[];
            failed?: boolean;
            /** @description Stack path → matched categories. */
            categories?: {
                [key: string]: components["schemas"]["Category"][];
            };
            /** @description Stack path → operation counts. */
            counts?: {
                [key: string]: components["schemas"]["Counts"];
            };
        };
        /** @description A slice of one stack's combined output. */
        LogChunk: {
            id: string;
            stack: string;
            data: string;
        };
        GateCheck: {
            pr: number;
            environment: string;
        };
        GateRevoke: {
            pr: number;
            environment: string;
        };
        /** @description One apply-lock claim row. */
        Claim: {
            environment: string;
            stack_path: string;
            owner_pr: number;
            /** Format: date-time */
            expires_at: string;
        };
        /** @description A passing gate check. */
        GateCheckOK: {
            /** @description Leased requester SA the apply impersonates; empty for a clean/no-gate pass. */
            requester: string;
        };
        /** @description Machine-readable error: HTTP status carries the coarse class, code the precise condition callers switch on. */
        CodedError: {
            /** @description e.g. GATE-001, GATE-002, GATE-003, SRV-001 */
            code: string;
            message: string;
        };
        ClaimsListRequest: {
            environment: string;
        };
        ClaimsReleaseRequest: {
            environment: string;
            pr: number;
            /** @description Empty releases all of the PR's claims in the environment. */
            stack: string;
        };
        /** @description One execution in a list view — everything but the graph and the rendered report. */
        ExecutionSummary: {
            id: string;
            repo: string;
            sha: string;
            pr: number;
            environment: string;
            /** @description The commit-status context the run drives (e.g. plan/<env>, apply/<env>, verify/<env>). */
            context: string;
            /** @description Execution-level status (in_progress/success/failure). */
            status: string;
            /** @description Current lifecycle phase ("" before the first phase event). */
            phase: string;
            /** Format: date-time */
            created_at: string;
            /** @description Id of the execution that superseded this one ("" when live). */
            superseded_by: string;
            log_url: string;
        };
        /** @description One gate target awaiting human action, with its PR context. */
        PendingApproval: {
            pr: number;
            environment: string;
            /** @description Repo of the PR's latest execution in this environment ("" when none). */
            repo: string;
            class: string;
            target: string;
            /** @description The approval-backend grant resource name ("" until a grant exists). */
            grant_name: string;
            /** @description Backend grant state (e.g. AWAITING, ACTIVATING, DENIED, REVOKED). */
            state: string;
            /** @description Leased requester SA for this grant. */
            requester: string;
        };
        /** @description PR-level identity as last reported by the GitHub webhook (title, author, branch, automerge). */
        PRMeta: {
            title: string;
            body: string;
            author_login: string;
            head_ref: string;
            url: string;
            auto_merge: boolean;
        };
        /** @description A PR's merge-readiness on this serve's tier. */
        PRMergeState: {
            /** @description This serve's tier (empty when the tier has none configured). */
            environment: string;
            /** @description The check name that gates merge (e.g. apply-lock/<env> or terraform/<env>). */
            required_check: string;
            /** @description GitHub check conclusion vocabulary; "" means still in progress. */
            check_conclusion: string;
            merge_blocked: boolean;
            /** @description Short human-readable blocker reason ("" when not blocked). */
            blocker: string;
        };
        /** @description A PR's identity and per-tier merge state. */
        PRView: {
            pr: number;
            /** @description Repo of the PR's latest execution ("" when none). */
            repo: string;
            meta?: components["schemas"]["PRMeta"];
            merge: components["schemas"]["PRMergeState"];
        };
        /** @description A database nullable int64, serialized raw (historical accident, preserved for wire compatibility). */
        NullInt64: {
            /** Format: int64 */
            Int64: number;
            Valid: boolean;
        };
        /** @description A recorded gate target with its grant state (PascalCase keys). */
        StoredGateTarget: {
            Class: string;
            Target: string;
            /** @description The approval-backend grant resource name (may be empty). */
            GrantName: string;
            /** @description Backend grant state (e.g. REQUESTED, ACTIVE, DENIED, REVOKED). */
            State: string;
            /** @description Leased requester SA for this grant. */
            Requester: string;
        };
        /** @description The full execution read. Top-level and gate keys are PascalCase with a raw NullInt64 (see getExecution). */
        ExecutionDetail: {
            ID: string;
            Repo: string;
            SHA: string;
            PR: number;
            Environment: string;
            CheckRunID: components["schemas"]["NullInt64"];
            Rev: number;
            ReportMarkdown: string;
            LogURL: string;
            /** @description Execution-level status (in_progress/success/failure). */
            Status: string;
            StatusContext: string;
            Phase: string;
            /** Format: date-time */
            CreatedAt: string;
            SupersededBy: string;
            /** @description Latest verify execution for the same (pr, environment), "" when none. Additive (2026-07) — snake_case unlike its legacy siblings. */
            verify_execution_id: string;
            graph: components["schemas"]["Graph"];
            gates: components["schemas"]["StoredGateTarget"][];
        };
        InspectGrant: {
            pr: number;
            environment: string;
            class: string;
            target: string;
            grant_name: string;
            state: string;
            requester: string;
            drift_detected?: boolean;
            actual_state?: string;
        };
        InspectGateDetail: {
            pr: number;
            environment: string;
            gate_state: string;
            targets: components["schemas"]["InspectGateTarget"][];
            reasons: components["schemas"]["InspectGateReason"][];
        };
        InspectGateTarget: {
            class: string;
            target: string;
            grant_name: string;
            state: string;
            requester: string;
        };
        InspectGateReason: {
            event_type: string;
            /** Format: date-time */
            occurred_at: string;
            description: string;
        };
        InspectClaimsSet: {
            environment: string;
            claims: components["schemas"]["InspectClaim"][];
        };
        InspectClaim: {
            stack: string;
            pr: number;
            /** Format: date-time */
            expires_at: string;
        };
        InspectEvent: {
            version: number;
            type: string;
            /** Format: date-time */
            occurred_at: string;
            data: Record<string, never>;
        };
        InspectPRSummary: {
            pr: number;
            repo: string;
            meta?: components["schemas"]["PRMeta"];
            gate_state: string;
            open_grants: components["schemas"]["InspectGrant"][];
            claims: components["schemas"]["InspectClaim"][];
            executions: components["schemas"]["ExecutionSummary"][];
        };
        InspectPoolSet: {
            environment: string;
            slots: components["schemas"]["InspectPoolSlot"][];
            waiting: components["schemas"]["InspectPoolWaitingPR"][];
        };
        InspectPoolSlot: {
            requester: string;
            occupied: boolean;
            pr?: number;
            environment?: string;
            grant_name?: string;
            state?: string;
            elapsed_seconds?: number;
        };
        InspectPoolWaitingPR: {
            pr: number;
            environment: string;
            reason: string;
            blocker_pr: number;
            blocker_env: string;
        };
    };
    responses: {
        /** @description Malformed payload (decode/validation error as plain text). */
        BadRequestText: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": unknown;
            };
        };
        /** @description Server-side failure (plain-text message). */
        InternalText: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": unknown;
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    initExecution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Init"];
            };
        };
        responses: {
            /** @description Recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestText"];
            500: components["responses"]["InternalText"];
            /** @description The GitHub check run could not be created. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    reportPhase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhaseEvent"];
            };
        };
        responses: {
            /** @description Recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestText"];
            500: components["responses"]["InternalText"];
            /** @description The GitHub check run could not be created. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    updateStack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Update"];
            };
        };
        responses: {
            /** @description Recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestText"];
            500: components["responses"]["InternalText"];
        };
    };
    finalizeExecution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Finalize"];
            };
        };
        responses: {
            /** @description Recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestText"];
            500: components["responses"]["InternalText"];
        };
    };
    appendLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogChunk"];
            };
        };
        responses: {
            /** @description Appended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestText"];
            500: components["responses"]["InternalText"];
        };
    };
    checkGate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateCheck"];
            };
        };
        responses: {
            /** @description Gate satisfied; apply may proceed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateCheckOK"];
                };
            };
            400: components["responses"]["BadRequestText"];
            /** @description Gate not passable: `GATE-001` (never classified) or `GATE-002` (a required grant is not ACTIVE). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodedError"];
                };
            };
            /** @description Internal error (`SRV-001`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodedError"];
                };
            };
            /** @description Gate state could not be freshly confirmed (`GATE-003`) — transient, retriable, fail-closed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodedError"];
                };
            };
        };
    };
    revokeGate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateRevoke"];
            };
        };
        responses: {
            /** @description Accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestText"];
        };
    };
    listClaims: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimsListRequest"];
            };
        };
        responses: {
            /** @description The environment's claims. Always a JSON array, never null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"][];
                };
            };
            400: components["responses"]["BadRequestText"];
            500: components["responses"]["InternalText"];
        };
    };
    releaseClaims: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimsReleaseRequest"];
            };
        };
        responses: {
            /** @description Accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestText"];
        };
    };
    listExecutions: {
        parameters: {
            query?: {
                /** @description Only executions for this pull request. */
                pr?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution summaries, newest first. Always an array, never null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionSummary"][];
                };
            };
            400: components["responses"]["BadRequestText"];
            500: components["responses"]["InternalText"];
        };
    };
    listApprovals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending approvals. Always an array, never null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingApproval"][];
                };
            };
            500: components["responses"]["InternalText"];
        };
    };
    getPR: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The PR's identity and merge state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PRView"];
                };
            };
            /** @description Unknown PR. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
            500: components["responses"]["InternalText"];
        };
    };
    getExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The execution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionDetail"];
                };
            };
            /** @description Unknown execution id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
            500: components["responses"]["InternalText"];
        };
    };
    inspectGrants: {
        parameters: {
            query?: {
                state?: string;
                live?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectGrant"][];
                };
            };
        };
    };
    inspectGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pr: number;
                env: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectGateDetail"];
                };
            };
        };
    };
    inspectClaims: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                env: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectClaimsSet"];
                };
            };
        };
    };
    inspectEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                stream: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectEvent"][];
                };
            };
        };
    };
    inspectOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectPRSummary"][];
                };
            };
        };
    };
    inspectPool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectPoolSet"];
                };
            };
        };
    };
    adminGrantsRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminGrantsReleaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InternalText"];
            500: components["responses"]["InternalText"];
        };
    };
    adminExecutionsCancel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminExecutionsCancelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InternalText"];
            500: components["responses"]["InternalText"];
        };
    };
    adminGatesSatisfy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminGatesSatisfyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InternalText"];
            500: components["responses"]["InternalText"];
        };
    };
    adminChecksOverride: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminChecksOverrideRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InternalText"];
            500: components["responses"]["InternalText"];
        };
    };
}
